Homework3
artemon4uk/smart-home-2020 pull request #3
Opened 2020-03-21 14:47 UTC by artemon4uk

2020-03-23 11:27 UTC, a-ivanov requested changes

2020-03-23 11:27 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/State.java
> +    protected Signalization signalization;
Класс ради одного поля - не имеет смысла, а минусы см. Effective Java Item 20, можно сделать состояние - интерфейсом.

2020-03-23 11:27 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Decorator.java
> +            Sender sender = new Sender();
Лучше передавать полем в конструкторе.

2020-03-23 11:27 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Decorator.java
> +            sender.sendSMS();
А где возможность деактивировать сигнализацию спец событием?

2020-03-23 11:27 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Signalization.java
> +    public void changeState(State state) {
Т.е. клиент может вот так легко поменять код? Исправьте http://bit.ly/3aTPNOi

2020-03-23 11:27 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Signalization.java
> +    public boolean checkEqualsCode(String newCode) {
Это тоже лучше не выдавать наружу.

2020-03-23 11:27 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Signalization.java
> +    public void changeState(State state) {
Подумайте, где лучше хранить правильный код. Кто им пользуется?

2020-03-23 11:27 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Decorator.java
> +public class Decorator implements EventHandler {
Просто декоратор - плохое название, добавьте специфики.

2020-03-23 11:27 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +                new Decorator(smartHome, new DoorEventProcessor(smartHome)),
https://bit.ly/2UoOLDs Сделайте, чтобы смс отправлялось всего 1 раз.

2020-03-23 11:27 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/GeneratorEvent.java
> +    public static SensorEvent getNextSensorEvent() {
http://bit.ly/3aLBprl создайте инстанс класса в main.

2020-03-24 10:23 UTC, artemon4uk commented on src/main/java/ru/sbt/mipt/oop/Decorator.java
> +            sender.sendSMS();
Не очень понятно, что имеется в виду. В домашнем задании было сказано, что нужен декоратор такой, что, "если сигнализация находится в состоянии "активирована”, то любое событие от сенсоров (включение/выключение света, открытие/закрытие двери) должно переводить сигнализацию в режим тревоги" (за что отвечает первый if с условием на ActiveState), "отправлять смс уведомление" (за что отвечает второй if с условием на AlarmState) и "если сигнализация находится в режиме тревоги, то остальные обработчики событий должны игнорировать любые события, смс должны продолжать отправляться" (за это отвечает второй if с условием на AlarmState и else, чтобы это событие не было обработано в режиме сигнализации AlarmState).

2020-03-26 12:52 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Decorator.java
> +            sender.sendSMS();
Понял, значит это доп. требование, можно не делать.

2020-03-26 12:59 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Decorator.java
> +            sender.sendSMS();
Да, явно этого в задании не сказано. С другой стороны у вас есть событие ALARM_DEACTIVATE, которое, не работает так, как звучит. Т.е. после ALARM_ACTIVATE декоратор только шлет смс и в приложении пропадает возможность отключить сигнализацию. Тогда либо уберите событие ALARM_DEACTIVATE, либо добавьте его корректную обработку.

2020-03-26 13:00 UTC, a-ivanov requested changes
Решите с ALARM_DEACTIVATE (см. обсуждение) и зачет.

2020-03-30 14:29 UTC, a-ivanov approved these changes

2020-03-30 16:17 UTC, merged